# Site settings
title: Alexander Semenov
description: Get to know me
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alexander Semenov
user_description: My name is Alex, and I am studying for the Bachelor of Bioinformatics at the Technical University of Munich. My passions are Python development, data analysis, and blockchain technology. I'm interested in discovering new connections to exchange experiences, generate ideas, and grow together.
user_title: Bioinformatics, Python, Blockchain
email: mail@alexsemenov.de
twitter_username: ferrozinator21
# instagram_username:
#facebook_username: 
linkedin_username: semenov-alex
github_username:  Tsatsch
# medium_username: 
# medium_url: 
# gplus_username: 

exclude: ['package.json', 'src', 'node_modules', 'vendor']

