# Site settings
title: Alexander Semenov
description: Get to know me
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alexander Semenov
user_description: My name is Sascha, and I am currently pursuing an M.Sc. in Information Systems at the Technical University of Munich, where I previously earned a B.Sc. in Bioinformatics. I am passionate about Python development, data analysis, and Web3 technologies. As an active participant in the DeFi space and DAOs, I enjoy exploring the variety of web3 ecosystems around there. I am always eager to connect with like-minded individuals to exchange ideas, collaborate, and grow together.
user_title: Web3, Data Science, Information Systems
email: mail@alexsemenov.de
twitter_username: tsatscha
# instagram_username:
#facebook_username: 
linkedin_username: semenov-alex
github_username:  Tsatsch
# medium_username: 
# medium_url: 
# gplus_username: 

exclude: ['package.json', 'src', 'node_modules', 'vendor']

